In [41]:
import numpy as np

In [42]:
def movement():
  p_up = np.array([[0.9, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #0
                 [0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0], #1
                 [0, 0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0], #2
                 [0, 0, 0.1, 0, 0.9, 0, 0, 0, 0, 0, 0, 0],   #3
                 [0.8, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0],   #4
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],       #5
                 [0, 0, 0.8, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0], #6
                 [0, 0, 0, 0.8, 0, 0, 0.1, 0.1, 0, 0, 0, 0], #7
                 [0, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0.1, 0, 0], #8
                 [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0], #9
                 [0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0, 0.1], #10
                 [0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0.1]  #11
                 ])
  p_down = np.array([[0.1, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0],
                    [0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0.1, 0, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0],
                    [0, 0, 0.1, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0.2, 0, 0, 0, 0.8, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0.8, 0],
                    [0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0.8],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0.1, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.9],
                  ])
  p_left = np.array([[0.9, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
                    [0.8, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0.8, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0],
                    [0, 0, 0.8, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0],
                    [0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0],
                    [0, 0, 0, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0.1],
                    [0, 0, 0, 0, 0.1, 0, 0, 0, 0.9, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.2, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.8, 0.1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.8, 0.1],
                  ])
  p_right = np.array([[0.1, 0.8, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
                      [0, 0.2, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                      [0, 0, 0.1, 0.8, 0, 0, 0.1, 0, 0, 0, 0, 0],
                      [0, 0, 0, 0.9, 0, 0, 0, 0.1, 0, 0, 0, 0],
                      [0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0, 0, 0],
                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                      [0, 0, 0.1, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0],
                      [0, 0, 0, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1],
                      [0, 0, 0, 0, 0.1, 0, 0, 0, 0.1, 0.8, 0, 0],
                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.8, 0],
                      [0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0.1, 0.8],
                      [0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0.9],
                  ])
  p = [p_up, p_down, p_left, p_right]
  return p

In [43]:
def simulator(s, a):

  r = np.array([0, 0, 0, +1,
              0, 0, 0, -100,
              0, 0, 0, 0])
  
  p = movement()

 #0=up, 1=down, 2=left, 3=right

  snext = np.random.choice(12 ,p=p[a][s])
  
  return snext, r[snext]


In [44]:
def q_learning(Q, s, gamma):
  itrations = 2000
  #0=up, 1=down, 2=left, 3=right
  Q_0 = Q.copy()

  for i in range(itrations):

    epsilon = 1/(0.0002 * i + 1)
    alpha = 1/(0.0005 * i + 1000)

    if np.random.rand() < epsilon:
      a= np.random.randint(4)
    else:
      a = np.argmax(Q[s])

    snext, r = simulator(s, a)
    Q[s,a] = Q[s,a] + alpha*(r + gamma * np.max(Q[snext]) - Q[s,a])
    s = snext

  return Q, i

In [45]:
# declaring variables
gamma = 0.9 #discount factor for future rewards

s_init = np.random.randint(low=0, high=12, size=1).astype(np.int)
if s_init == 5: s_init = s_init + np.random.randint(-5, 7)
s = s_init[0]

Q = np.zeros((12, 4))

Q, i = q_learning(Q, s, gamma)


print(f'Number of iterations: {i+1}')

pi = np.argmax(Q, axis=1).reshape(3,4) + 1
pi[1,1] = 0

pi_print = pi.reshape(3,4)

Q_max = np.amax(Q[:], axis=1)
print(f'Q_max: \n{Q_max.reshape(3,4)}\n\n')

Q_print_up = Q[:,0].reshape(3,4)
Q_print_down = Q[:,1].reshape(3,4)
Q_print_left = Q[:,2].reshape(3,4)
Q_print_right = Q[:,3].reshape(3,4)

print(f'Q Table up: \n{Q_print_up}')
print(f'Q Table down: \n{Q_print_down}')
print(f'Q Table left: \n{Q_print_left}')
print(f'Q Table right: \n{Q_print_right}')

print(f'\nFinal Policy: \n{pi_print}\n0=Nothing, 1=up, 2=down, 3=left, 4=right')

pi_print_arrows = pi.reshape(3,4).astype(str)
pi_print_arrows[pi_print_arrows=='1']='\u2191'
pi_print_arrows[pi_print_arrows=='2']='\u2193'
pi_print_arrows[pi_print_arrows=='3']='\u2190'
pi_print_arrows[pi_print_arrows=='4']='\u2192'
print(f'\nFinal Policy: \n{pi_print_arrows}')

Number of iterations: 2000
Q_max: 
[[3.65095826e-05 1.67078713e-03 5.79492070e-02 2.64509978e-04]
 [3.38714189e-07 0.00000000e+00 7.48003567e-05 2.95022530e-03]
 [1.28475294e-09 1.89670853e-08 1.92570939e-06 2.09676484e-09]]


Q Table up: 
[[ 2.07964659e-07  8.35427608e-05  5.05230513e-03  2.64509978e-04]
 [ 3.38714189e-07  0.00000000e+00 -3.83565688e-01 -1.69325769e-01]
 [ 1.28475294e-09  1.14177700e-09  1.92570939e-06 -1.48339756e+00]]
Q Table down: 
[[ 1.61191799e-06  9.41446098e-05  9.77294460e-04 -2.66171778e+00]
 [ 3.25354295e-10  0.00000000e+00 -4.91743642e-01 -1.97675070e-01]
 [ 1.89881577e-11  4.25820412e-10  1.45845712e-08  2.09676484e-09]]
Q Table left: 
[[ 2.50874514e-07  4.69193515e-06  7.86857287e-05 -9.22897874e-02]
 [ 1.35659197e-08  0.00000000e+00  7.48003567e-05  2.95022530e-03]
 [ 2.03001244e-11  2.63535017e-11  7.62868265e-10 -9.96997166e-02]]
Q Table right: 
[[ 3.65095826e-05  1.67078713e-03  5.79492070e-02 -7.58007378e-02]
 [ 6.50490773e-08  0.00000000e+00 -4.4717