In [206]:
import numpy as np
import matplotlib.pyplot as plt

In [207]:
def policy_evaluation(pi, v, r, gamma):
    delta = 1
    while delta > thresh:
        v_0 = v.copy()
        for s in range(len(pi)):
            if pi[s] is not 0:
                v[s] = r[s] + gamma * sum_next_state_eval(v, pi, s)
        delta = max(abs(v - v_0))

    pi_print = np.zeros((3,4)).astype(np.int)
    k = 0
    for i in range(3):
      for j in range(4):
        pi_print[i,j]=pi[k]
        k += 1

    print(f'Policy: \n{pi_print}')

    V_print = np.zeros((3,4))
    k = 0
    for i in range(3):
      for j in range(4):
        V_print[i,j]=v[k]
        k += 1

    print(f'V for Policy above:\n{V_print}\n')
    return v

In [208]:
def sum_next_state_eval(v, pi, s):
    # 1=up, 2=down, 3=left, 4=right
    sum = 0
    action = pi[s]
    if action == 1:  # up
        if s == 0: sum = v[1] * 0.1 + v[0] * 0.9
        if s == 1: sum = v[0] * 0.1 + v[2] * 0.1 + v[1] * 0.8
        if s == 2: sum = v[1] * 0.1 + v[3] * 0.1 + v[2] * 0.8
        if s == 3: sum = v[2] * 0.1 + v[3] * 0.9
        if s == 4: sum = v[0] * 0.8 + v[4] * 0.2
        if s == 6: sum = v[2] * 0.8 + v[7] * 0.1 + v[6] * 0.1
        if s == 7: sum = v[6] * 0.1 + v[3] * 0.8 + v[7] * 0.1
        if s == 8: sum = v[4] * 0.8 + v[9] * 0.1 + v[8] * 0.1
        if s == 9: sum = v[8] * 0.1 + v[10] * 0.1 + v[9] * 0.8
        if s == 10: sum = v[9] * 0.1 + v[11] * 0.1 + v[6] * 0.8
        if s == 11: sum = v[10] * 0.1 + v[7] * 0.8 + v[11] * 0.1

    if action == 2:  # down
        if s == 0: sum = v[1] * 0.1 + v[4] * 0.8 + v[0] * 0.1
        if s == 1: sum = v[0] * 0.1 + v[2] * 0.1 + v[1] * 0.8
        if s == 2: sum = v[1] * 0.1 + v[3] * 0.1 + v[6] * 0.8
        if s == 3: sum = v[2] * 0.1 + v[7] * 0.8 + v[3] * 0.1
        if s == 4: sum = v[8] * 0.8 + v[4] * 0.2
        if s == 6: sum = v[10] * 0.8 + v[7] * 0.1 + v[6] * 0.1
        if s == 7: sum = v[6] * 0.1 + v[11] * 0.8 + v[7] * 0.1
        if s == 8: sum = v[9] * 0.1 + v[8] * 0.9
        if s == 9: sum = v[8] * 0.1 + v[10] * 0.1 + v[9] * 0.8
        if s == 10: sum = v[9] * 0.1 + v[11] * 0.1 + v[10] * 0.8
        if s == 11: sum = v[10] * 0.1 + v[11] * 0.9

    if action == 3:  # left
        if s == 0: sum = v[4] * 0.1 + v[0] * 0.9
        if s == 1: sum = v[0] * 0.8 + v[1] * 0.2
        if s == 2: sum = v[6] * 0.1 + v[2] * 0.8 + v[2] * 0.1
        if s == 3: sum = v[7] * 0.1 + v[2] * 0.8 + v[3] * 0.1
        if s == 4: sum = v[0] * 0.1 + v[8] * 0.1 + v[4] * 0.8
        if s == 6: sum = v[2] * 0.1 + v[10] * 0.1 + v[6] * 0.8
        if s == 7: sum = v[3] * 0.1 + v[6] * 0.8 + v[11] * 0.1
        if s == 8: sum = v[4] * 0.1 + v[8] * 0.9
        if s == 9: sum = v[8] * 0.8 + v[9] * 0.2
        if s == 10: sum = v[9] * 0.8 + v[6] * 0.1 + v[10] * 0.1
        if s == 11: sum = v[10] * 0.8 + v[7] * 0.1 + v[11] * 0.1

    if action == 4:  # right
        if s == 0: sum = v[1] * 0.8 + v[4] * 0.1 + v[0] * 0.1
        if s == 1: sum = v[2] * 0.8 + v[1] * 0.2
        if s == 2: sum = v[6] * 0.1 + v[3] * 0.8 + v[2] * 0.1
        if s == 3: sum = v[7] * 0.1 + v[3] * 0.9
        if s == 4: sum = v[8] * 0.1 + v[0] * 0.1 + v[4] * 0.8
        if s == 6: sum = v[10] * 0.1 + v[7] * 0.8 + v[2] * 0.1
        if s == 7: sum = v[11] * 0.1 + v[3] * 0.1 + v[7] * 0.8
        if s == 8: sum = v[9] * 0.8 + v[4] * 0.1 + v[8] * 0.1
        if s == 9: sum = v[10] * 0.8 + v[9] * 0.2
        if s == 10: sum = v[6] * 0.1 + v[11] * 0.8 + v[10] * 0.1
        if s == 11: sum = v[7] * 0.1 + v[11] * 0.9

    return sum

In [209]:
def policy_improvement(pi, v, r, gamma):
    equal_arrays = False
    best_action = [0, 0, 0, 0]
    Iterations = 1
    while equal_arrays != True:
        print(f'Policy iteration {Iterations}:')
        pi_0 = pi.copy()
        v = policy_evaluation(pi, v, r, gamma)
        for s in range(len(pi)):
            if pi[s] != 0:
                for a in range(1, 5):
                    b_a = r[s] + gamma * sum_next_state_impr(v, a, s)
                    best_action[a - 1] = b_a
                pi[s] = np.argmax(best_action) + 1
        delta = pi - pi_0
        comparison = delta == np.zeros(12)
        equal_arrays = comparison.all()
        Iterations += 1

    return pi

In [210]:
def sum_next_state_impr(v, a, s):
    # 1=up, 2=down, 3=left, 4=right
    sum = 0
    action = a
    if action == 1:  # up
        if s == 0: sum = v[1] * 0.1 + v[0] * 0.9
        if s == 1: sum = v[0] * 0.1 + v[2] * 0.1 + v[1] * 0.8
        if s == 2: sum = v[1] * 0.1 + v[3] * 0.1 + v[2] * 0.8
        if s == 3: sum = v[2] * 0.1 + v[3] * 0.9
        if s == 4: sum = v[0] * 0.8 + v[4] * 0.2
        if s == 6: sum = v[2] * 0.8 + v[7] * 0.1 + v[6] * 0.1
        if s == 7: sum = v[6] * 0.1 + v[3] * 0.8 + v[7] * 0.1
        if s == 8: sum = v[4] * 0.8 + v[9] * 0.1 + v[8] * 0.1
        if s == 9: sum = v[8] * 0.1 + v[10] * 0.1 + v[9] * 0.8
        if s == 10: sum = v[9] * 0.1 + v[11] * 0.1 + v[6] * 0.8
        if s == 11: sum = v[10] * 0.1 + v[7] * 0.8 + v[11] * 0.1

    if action == 2:  # down
        if s == 0: sum = v[1] * 0.1 + v[4] * 0.8 + v[0] * 0.1
        if s == 1: sum = v[0] * 0.1 + v[2] * 0.1 + v[1] * 0.8
        if s == 2: sum = v[1] * 0.1 + v[3] * 0.1 + v[6] * 0.8
        if s == 3: sum = v[2] * 0.1 + v[7] * 0.8 + v[3] * 0.1
        if s == 4: sum = v[8] * 0.8 + v[4] * 0.2
        if s == 6: sum = v[10] * 0.8 + v[7] * 0.1 + v[6] * 0.1
        if s == 7: sum = v[6] * 0.1 + v[11] * 0.8 + v[7] * 0.1
        if s == 8: sum = v[9] * 0.1 + v[8] * 0.9
        if s == 9: sum = v[8] * 0.1 + v[10] * 0.1 + v[9] * 0.8
        if s == 10: sum = v[9] * 0.1 + v[11] * 0.1 + v[10] * 0.8
        if s == 11: sum = v[10] * 0.1 + v[11] * 0.9

    if action == 3:  # left
        if s == 0: sum = v[4] * 0.1 + v[0] * 0.9
        if s == 1: sum = v[0] * 0.8 + v[1] * 0.2
        if s == 2: sum = v[6] * 0.1 + v[2] * 0.8 + v[2] * 0.1
        if s == 3: sum = v[7] * 0.1 + v[2] * 0.8 + v[3] * 0.1
        if s == 4: sum = v[0] * 0.1 + v[8] * 0.1 + v[4] * 0.8
        if s == 6: sum = v[2] * 0.1 + v[10] * 0.1 + v[6] * 0.8
        if s == 7: sum = v[3] * 0.1 + v[6] * 0.8 + v[11] * 0.1
        if s == 8: sum = v[4] * 0.1 + v[8] * 0.9
        if s == 9: sum = v[8] * 0.8 + v[9] * 0.2
        if s == 10: sum = v[9] * 0.8 + v[6] * 0.1 + v[10] * 0.1
        if s == 11: sum = v[10] * 0.8 + v[7] * 0.1 + v[11] * 0.1

    if action == 4:  # right
        if s == 0: sum = v[1] * 0.8 + v[4] * 0.1 + v[0] * 0.1
        if s == 1: sum = v[2] * 0.8 + v[1] * 0.2
        if s == 2: sum = v[6] * 0.1 + v[3] * 0.8 + v[2] * 0.1
        if s == 3: sum = v[7] * 0.1 + v[3] * 0.9
        if s == 4: sum = v[8] * 0.1 + v[0] * 0.1 + v[4] * 0.8
        if s == 6: sum = v[10] * 0.1 + v[7] * 0.8 + v[2] * 0.1
        if s == 7: sum = v[11] * 0.1 + v[3] * 0.1 + v[7] * 0.8
        if s == 8: sum = v[9] * 0.8 + v[4] * 0.1 + v[8] * 0.1
        if s == 9: sum = v[10] * 0.8 + v[9] * 0.2
        if s == 10: sum = v[6] * 0.1 + v[11] * 0.8 + v[10] * 0.1
        if s == 11: sum = v[7] * 0.1 + v[11] * 0.9

    return sum

In [211]:
# declaring variables
gamma = 0.9
thresh = 0.01

# 0=Nothing, 1=up, 2=down, 3=left, 4=right
pi = np.random.randint(low=1, high=5, size=12).astype(np.int)
pi[5] = 0

v = np.zeros(12)

r = np.array([0, 0, 0, +1,
              0, 0, 0, -100,
              0, 0, 0, 0])

pi = policy_improvement(pi, v, r, gamma)

pi_print = np.zeros((3,4)).astype(np.int)
k = 0
for i in range(3):
  for j in range(4):
    pi_print[i,j]=pi[k]
    k += 1

print(f'Final Policy: \n{pi_print}\n0=Nothing, 1=up, 2=down, 3=left, 4=right')

pi_print_arrows = pi.reshape(3,4).astype(str)
pi_print_arrows[pi_print_arrows=='1']='\u2191'
pi_print_arrows[pi_print_arrows=='2']='\u2193'
pi_print_arrows[pi_print_arrows=='3']='\u2190'
pi_print_arrows[pi_print_arrows=='4']='\u2192'
print(f'\nFinal Policy: \n{pi_print_arrows}')

Policy iteration 1:
Policy: 
[[4 3 3 1]
 [2 0 3 3]
 [2 1 2 1]]
V for Policy above:
[[  -1.77058236   -1.55358299   -6.30684162    2.31248506]
 [  -5.52770337    0.          -13.40446569 -118.17311289]
 [  -6.30684162  -13.40446569  -35.46842205  -97.00682052]]

Policy iteration 2:
Policy: 
[[1 3 4 1]
 [1 0 3 1]
 [3 3 3 3]]
V for Policy above:
[[-1.97616373e-02 -1.78294849e-02  6.96084771e+00  8.52214420e+00]
 [-1.78294849e-02  0.00000000e+00  2.29081355e+00 -1.02921517e+02]
 [-1.89156944e-02 -1.70968822e-02  2.12805507e-01 -1.00109397e+01]]

Policy iteration 3:
Policy: 
[[2 4 4 1]
 [3 0 3 3]
 [4 4 1 2]]
V for Policy above:
[[  1.44626191   6.27090575   7.14349625   8.6421739 ]
 [  1.04967018   0.           3.10425997 -96.88304951]
 [  1.86209825   2.22620771   2.53951353   1.1653452 ]]

Policy iteration 4:
Policy: 
[[4 4 4 1]
 [2 0 3 3]
 [4 4 1 2]]
V for Policy above:
[[  5.1320503    6.2756681    7.14822345   8.64631702]
 [  1.69780639   0.           3.1133575  -96.87324779]
 [  1.936