In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def ac_va_iter(pi, Q, r, p, gamma, thresh):
  delta = 1
  #1=up, 2=down, 3=left, 4=right
  while delta > thresh:
      Q_0 = Q.copy()
      for s in range(Q.shape[0]):
        if s != 5:
          for a in range(Q.shape[1]):
            p_vec = p[a][s]
            #Q[s,a] = r[s]-int(s!=3)*50 + gamma * np.sum(p_vec[p_vec>0]*np.max(Q[p_vec>0], axis=1))      #tryout for adding a negativ reward component
            Q[s,a] = r[s] + gamma * np.sum(p_vec[p_vec>0]*np.max(Q[p_vec>0], axis=1))
      delta = np.max(np.abs(Q - Q_0))

  pi = np.argmax(Q, axis=1).reshape(3,4) + 1
  pi[1,1] = 0

  return pi, Q

In [3]:
# declaring variables
gamma = 0.9
thresh = 0.01

# 0=Nothing, 1=up, 2=down, 3=left, 4=right
pi = np.random.randint(low=1, high=5, size=12).astype(np.int)
pi[5] = 0

Q = np.zeros((12, 4))

r = np.array([0, 0, 0, +1,
              0, 0, 0, -100,
              0, 0, 0, 0])
"""
disc = -200
r_disc = np.array([disc, disc, disc, +1,
              disc, disc, disc, -100,
              disc, disc, disc, disc])

r= r_disc
"""

p_up = np.array([[0.9, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0.1, 0, 0.9, 0, 0, 0, 0, 0, 0, 0],
                 [0.8, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 [0, 0, 0.8, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0],
                 [0, 0, 0, 0.8, 0, 0, 0.1, 0.1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0.1, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0],
                 [0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0, 0.1],
                 [0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0.1]
                 ])
p_down = np.array([[0.1, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0],
                   [0.1, 0.8, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0.1, 0, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0],
                   [0, 0, 0.1, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0.2, 0, 0, 0, 0.8, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0.8, 0],
                   [0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0.8],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0.1, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.8, 0.1],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.9],
                 ])
p_left = np.array([[0.9, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
                   [0.8, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0.8, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0],
                   [0, 0, 0.8, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0],
                   [0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0],
                   [0, 0, 0, 0.1, 0, 0, 0.8, 0, 0, 0, 0, 0.1],
                   [0, 0, 0, 0, 0.1, 0, 0, 0, 0.9, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.2, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.8, 0.1, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.8, 0.1],
                 ])
p_right = np.array([[0.1, 0.8, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0.2, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0.1, 0.8, 0, 0, 0.1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0.9, 0, 0, 0, 0.1, 0, 0, 0, 0],
                    [0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0.1, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0],
                    [0, 0, 0, 0.1, 0, 0, 0, 0.8, 0, 0, 0, 0.1],
                    [0, 0, 0, 0, 0.1, 0, 0, 0, 0.1, 0.8, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.8, 0],
                    [0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0.1, 0.8],
                    [0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0.9],
                 ])

p = [p_up, p_down, p_left, p_right]

pi, Q = ac_va_iter(pi, Q, r, p, gamma, thresh)

pi_print = pi.reshape(3,4)

Q_print_up = Q[:,0].reshape(3,4)
Q_print_down = Q[:,1].reshape(3,4)
Q_print_left = Q[:,2].reshape(3,4)
Q_print_right = Q[:,3].reshape(3,4)

print(f'Q Table up: \n{Q_print_up}')
print(f'Q Table down: \n{Q_print_down}')
print(f'Q Table left: \n{Q_print_left}')
print(f'Q Table right: \n{Q_print_right}')

print(f'\nFinal Policy: \n{pi_print}\n0=Nothing, 1=up, 2=down, 3=left, 4=right')

pi_print_arrows = pi.reshape(3,4).astype(str)
pi_print_arrows[pi_print_arrows=='1']='\u2191'
pi_print_arrows[pi_print_arrows=='2']='\u2193'
pi_print_arrows[pi_print_arrows=='3']='\u2190'
pi_print_arrows[pi_print_arrows=='4']='\u2192'
print(f'\nFinal Policy: \n{pi_print_arrows}')

Q Table up: 
[[   1.14215801    1.31053779    1.51665565    2.03743276]
 [   1.10265502    0.           -7.65719363 -107.39805068]
 [   0.95370789    0.74850419    0.64588761  -71.36251716]]
Q Table down: 
[[   1.03112567    1.31053779    0.85083654  -70.12782376]
 [   0.87979643    0.           -8.34077848 -108.63770462]
 [   0.84713484    0.74850419    0.62859669    0.3218842 ]]
Q Table left: 
[[  1.10976231   1.16744643   1.27142009  -6.54087811]
 [  0.99228703   0.           0.75311316 -99.24597737]
 [  0.87174234   0.83593259   0.73527047  -8.37377365]]
Q Table right: 
[[   1.2578956     1.46400812    1.67852139   -6.28246192]
 [   0.99228703    0.          -71.24557389 -171.24532255]
 [   0.78212432    0.67541842    0.36125218   -8.67141176]]

Final Policy: 
[[4 4 4 1]
 [1 0 3 3]
 [1 3 3 2]]
0=Nothing, 1=up, 2=down, 3=left, 4=right

Final Policy: 
[['→' '→' '→' '↑']
 ['↑' '0' '←' '←']
 ['↑' '←' '←' '↓']]
